fjrdomingues/autopilot

.env.template, README.md, createSummaryOfFiles.js, package-lock.json, package.json
Move Include/Exclude file lists to config.
Allow CODE_DIR to either be configured in code (recommended in README) or by CLI parameter.
Use a CLI parameter lib to have help etc.
https://github.com/fjrdomingues/autopilot/issues/5
https://github.com/fjrdomingues/autopilot/issues/10
=> Refactor several config parameters for ease of use

modules/gpt.js
This might need to be merged after one or more of the other PRs
https://github.com/fjrdomingues/autopilot/pull/6/files
https://github.com/fjrdomingues/autopilot/pull/13/files - This one always passes the model to callGPT
=> cleanup default models

.env.template, README.md, createSummaryOfFiles.js, modules/gpt.js, package-lock.json, package.json
**Note:** This is after merging all the other PRs, probably merged the others then re-diff the PR
(or use it to get all the work so far as one)
Let Summary control the model it uses, and add config and a parameter to control it.
This is half of https://github.com/fjrdomingues/autopilot/issues/9
=> !!Feature/summary model refactor

createSummaryOfFiles.js
The function already accounts for the modules when provided with all the paramters
=> Cleanup cost call

modules/gpt.js
This is highly likely to change and should be prominent
I also think you can put the max text length into it and use it (might need some refactoring, didn't check)  https://github.com/fjrdomingues/autopilot/commit/332bda909faddf463985f5aa9ba13b350a757e1b#diff-58dfb16816359b5fea899e5c5f017902a2ffbf625bcee6398fe1784b96fce72aR44
=> Move const modelCostMap up

.env.template, agents/codeReader.js, agents/coder.js, agents/getFiles.js, agents/taskComplexity.js
Extract agent models to config
=> Extract agent models to config

agents/taskComplexity.js
Put a spell checker on the IDE ;)
=> spelling fixes

agents/codeReader.js.ai.txt, agents/coder.js.ai.txt, agents/getFiles.js.ai.txt, agents/index.js.ai.txt, agents/taskComplexity.js.ai.txt, createSummaryOfFiles.js, createSummaryOfFiles.js.ai.txt, modules/gpt.js.ai.txt, ui.js.ai.txt
Changed summary prompt to produce smaller summaries and fixed the filename of the summary (.js was hardcoded)
=> changed summary prompt and file extension

ui.js
Use a `__DO_NOT_REMOVE__` file vs FS access to check and create a directory
=> Cleaned suggestions dir access

README.md, ui.js
- Changed default to no-interactive
- non-interactive was broken
- changed readline to prompts
- Added open to abort program
=> fix no-interactive and added prompts

modules/summaries.js, ui.js
We now split long summaries into chunks and run them by the file selection agent chunk by chunk, adding the selected files.
This enables code repos with a large number of files, or just long-generated summaries. (up to max size per file)
=> Summaries chunks

agents/genericAgent.js, agents/reviewer.js, benchmarks/summary_chunks.js, modules/fsOutput.js, package.json, ui.js
- Added diff generator to tests
- Changes how reviewer works
- Added new test (needs improv)
=> Refactored tests

agents/codeReader.js, agents/getFiles.js, agents/indexer.js, agents/reviewer.js, agents/taskComplexity.js, benchmarks/files/ui.js, createSummaryOfFiles.js, modules/directoryHelper.js, modules/fsInput.js, modules/gpt.js, modules/hashing.js, modules/summaries.js, modules/tokenHelper.js, package-lock.json
This is a bit of groundwork to simplify https://github.com/fjrdomingues/autopilot/issues/80 and https://github.com/fjrdomingues/autopilot/issues/70.
* Extracted agent/indexer
* maxTokenSingleFile const
* getFilePaths - central function to deal with the include/exclude logic
* hashFile - prep identifier for future file differences checking logic.
* loadFiles - central get all files content and process token counts and hash.
* simplify processDirectory
* simplify cost estimation and directory token counting
* rename approveIndexing user input
* fullAnalysis -> indexFullProject
=> Refactor indexer

modules/codeBase.js, modules/db.js
@fjrdomingues 
Didn't test but should solve that issue
https://github.com/fjrdomingues/autopilot/issues/103
=> hash over timestamp for accurate file changes

ui.js
Provide good messages for the cases of no files selected and bad files selected by the agent
https://github.com/fjrdomingues/autopilot/issues/114
https://github.com/fjrdomingues/autopilot/issues/117
=> no files ux messages

.env.template, modules/summaries.js
https://github.com/fjrdomingues/autopilot/issues/115
=> Move max token const to env

modules/codeBase.js, modules/db.js, ui.js
Implement Interactive gapfill
Will avoid some user issues
https://github.com/fjrdomingues/autopilot/issues/109
https://github.com/fjrdomingues/autopilot/issues/110
=> Interactive gapfill

.env.template, agents/codeReader.js, agents/coder.js, agents/getFiles.js, agents/indexer.js, agents/reviewer.js, agents/taskComplexity.js, modules/codeBase.js, modules/init.js, modules/summaries.js, ui.js
@fjrdomingues 
https://github.com/fjrdomingues/autopilot/issues/104
Simplify the code model selection
Each agent has its own config module, no more cheap/advanced which was kinda random anyway
Didn't test
=> Simplify model selection

.env.template, agents/indexer.js, modules/db.js, modules/model.js, modules/summaries.js
* Important fixes to the langchain OpenAI calls
Extended summary to include
* Functions - tasks like in https://github.com/fjrdomingues/autopilot/issues/114 would benefit.
* dependenciesLibs - ground work for cascading updates.
* Keywords added - While I think this would help some higher level tasks, I don't have a test case at the moment, it could be groundwork for scoring tasks to summary match...
=> Extended summary

.env.template
In response to https://github.com/fjrdomingues/autopilot/issues/132 I think this is a better starting point for now. More info in the ticket.
We got 4k
We want the biggest file size to be able to edit
So 2k for the response.
That means the biggest file we can edit <2k
And Summaries < 2k, IDK how we get 800 tokens extra, but 🤷 should be no issue with 1k summaries I think.
=> Better Defaults

modules/db.js, modules/init.js, ui.js
* Always try to recreate db table. https://github.com/fjrdomingues/autopilot/issues/109
* Try to simplify the code a bit 
* Spin off some functionality into new functions: approveGapFill, indexGapFill, countTokensOfFilesToIndex
* Redo a couple of conditions for an easier read / reduced complexity
Needs testing
=> Better init

modules/interactiveGapFill.js
=> Fix gapFill delete

modules/summaries.js, modules/summaries.test.js
* Fix summary chunking
* Fill the original intent
* Be accurate
* Remove last delimiters
* Add unit tests for summary chunking
=> Fix summary chunking

ui.js
* Remove duplicate file recommendations
* Remove files that don't exist on the filesystem
https://github.com/fjrdomingues/autopilot/issues/156
=> sanitize file list

agents/advisor.js, agents/finalAdvisor.js, agents/getFiles.js, agents/getFiles.test.js, modules/fsInput.js, modules/gpt.js, ui.js
Changes:
- Added a new agent: finalAdvisor that merges the work of all individual advisors
- main function now return the tokens spent on a task. #127 
- fixed the test for getFiles (all tests pass with gpt3.5 and gpt4)
- Changed some prompts structure
This includes the previous PR I had opened so I'm closing it.
@hatkyinc2 good thinking on the way you added tests for the agents. Great work imo.
=> Return tokens usage and improved prompts
